services:
  - type: web
    name: RV There Yet
    runtime: node
    plan: free
    root: .
    build:
      command: npm install
    start: npm start
    envVars:
      - key: SMTP_HOST
        scope: build,runtime
      - key: SMTP_PORT
        scope: build,runtime
      - key: SMTP_SECURE
        scope: build,runtime
      - key: SMTP_USER
        scope: build,runtime
      - key: SMTP_PASS
        scope: build,runtime
      - key: SMTP_FROM_EMAIL
        scope: build,runtime
